import { describe, expect, it } from 'bun:test';
import type {
  DribbbleDesign,
  StitchDesign,
  SelectedDesign,
  ComponentLibrary,
  ComponentLibraryEntry,
} from '../src/types/index.mts';

describe(`Design types`, () => {
  it(`should create a valid DribbbleDesign`, () => {
    const design: DribbbleDesign = {
      title: `Admin Dashboard`,
      url: `https://dribbble.com/shots/12345`,
      imageUrl: `https://cdn.dribbble.com/img.jpg`,
      author: `Designer`,
      description: `A clean admin dashboard`,
      tags: [`dashboard`, `admin`],
    };

    expect(design.title).toBe(`Admin Dashboard`);
    expect(design.tags.length).toBe(2);
  });

  it(`should create a valid StitchDesign`, () => {
    const design: StitchDesign = {
      id: `01ABC`,
      name: `Portal Variation 1`,
      previewUrl: `https://stitch.withgoogle.com/preview/01ABC`,
      editUrl: `https://stitch.withgoogle.com/edit/01ABC`,
      thumbnailDataUri: `data:image/png;base64,...`,
      description: `Generated by Gemini 3.1 Pro`,
    };

    expect(design.id).toBe(`01ABC`);
    expect(design.description).toContain(`Gemini`);
  });

  it(`should create a valid SelectedDesign`, () => {
    const selected: SelectedDesign = {
      source: `stitch`,
      inspiration: {
        title: `Inspiration`,
        url: `https://dribbble.com/shots/1`,
        imageUrl: ``,
        author: `Author`,
        description: ``,
        tags: [],
      },
      chosen: {
        id: `01XYZ`,
        name: `Chosen Design`,
        previewUrl: ``,
        editUrl: ``,
        thumbnailDataUri: ``,
        description: ``,
      },
    };

    expect(selected.source).toBe(`stitch`);
    expect(selected.inspiration.title).toBe(`Inspiration`);
    expect(selected.chosen.id).toBe(`01XYZ`);
  });

  it(`should create a valid ComponentLibrary`, () => {
    const entry: ComponentLibraryEntry = {
      name: `card`,
      selector: `app-card`,
      category: `data-display`,
      files: [
        { path: `src/app/shared/components/card/card.component.ts`, content: `export class CardComponent {}` },
        { path: `src/app/shared/components/card/card.component.html`, content: `<div></div>` },
        { path: `src/app/shared/components/card/card.component.scss`, content: `:host { display: block; }` },
      ],
    };

    const library: ComponentLibrary = {
      designTokens: {
        path: `src/app/shared/styles/_tokens.scss`,
        content: `:root { --color-primary: #1976d2; }`,
      },
      components: [entry],
    };

    expect(library.components.length).toBe(1);
    expect(library.components[0]?.files.length).toBe(3);
    expect(library.designTokens.path).toContain(`_tokens`);
  });
});
