import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { Logger } from 'winston';
import type {
  SelectedDesign,
  ComponentLibrary,
  SpaFramework,
} from '../types/index.mts';

interface DecisionContext {
  readonly runId: string;
  readonly projectTitle: string;
  readonly framework: SpaFramework;
  readonly selectedDesign: SelectedDesign;
  readonly componentLibrary: ComponentLibrary | undefined;
  readonly allDesignUrls: readonly { name: string; url: string }[];
}

/**
 * Saves design decisions and color palette to `.doc/` markdown files
 * inside the workspace output directory.
 *
 * Creates:
 *   - `.doc/decisions.md`     — records which design was selected, why, and links
 *   - `.doc/color-palette.md` — extracted color tokens from the selected design
 */
export async function saveDecisions(
  outputDir: string,
  ctx: DecisionContext,
  logger: Logger,
): Promise<void> {
  const docDir = join(outputDir, `.doc`);
  await mkdir(docDir, { recursive: true });

  // ── color-palette.md ──────────────────────────────────────────
  const colorPalettePath = join(docDir, `color-palette.md`);
  const colorPaletteContent = buildColorPalette(ctx);
  await writeFile(colorPalettePath, colorPaletteContent);
  logger.info(`Saved color palette: ${colorPalettePath}`);

  // ── decisions.md ──────────────────────────────────────────────
  const decisionsPath = join(docDir, `decisions.md`);
  const decisionsContent = buildDecisions(ctx);
  await writeFile(decisionsPath, decisionsContent);
  logger.info(`Saved decisions: ${decisionsPath}`);
}

function buildDecisions(ctx: DecisionContext): string {
  const { runId, projectTitle, framework, selectedDesign, allDesignUrls } = ctx;
  const now = new Date().toISOString();

  const candidateList = allDesignUrls
    .map((d, i) => {
      const selected = d.url === selectedDesign.chosen.previewUrl ? ` **<-- SELECTED**` : ``;
      return `| ${i + 1} | ${d.name} | [Open in Stitch](${d.url}) |${selected}`;
    })
    .join(`\n`);

  return `# Design Decisions

> Auto-generated by angular-generator-agent on ${now}
> Run ID: \`${runId}\`

## Project

- **Title:** ${projectTitle}
- **Framework:** ${framework}

## Selected Design

- **Name:** ${selectedDesign.chosen.name}
- **Stitch URL:** [${selectedDesign.chosen.previewUrl}](${selectedDesign.chosen.previewUrl})
- **Inspiration (Dribbble):** [${selectedDesign.inspiration.title}](${selectedDesign.inspiration.url}) by ${selectedDesign.inspiration.author}
- **Description:** ${selectedDesign.chosen.description}

## Color Palette

See [color-palette.md](./color-palette.md) for the full token reference.

## All Candidate Designs

| # | Direction | Stitch URL | |
|---|-----------|------------|-|
${candidateList}

## Rationale

The design was selected by the user after reviewing all ${allDesignUrls.length} variations
in separate browser tabs on stitch.withgoogle.com. Each design included a landing page
as the first screen, followed by the main dashboard and key application screens.
`;
}

function buildColorPalette(ctx: DecisionContext): string {
  const { selectedDesign, componentLibrary } = ctx;
  const now = new Date().toISOString();

  // Try to extract colors from the component library's design tokens
  let tokenBlock = `No component library generated yet — colors listed below are from the design direction.`;
  const colors: { variable: string; value: string; usage: string }[] = [];

  if (componentLibrary) {
    const tokenContent = componentLibrary.designTokens.content;
    tokenBlock = `Extracted from \`${componentLibrary.designTokens.path}\`:\n\n\`\`\`scss\n${tokenContent}\n\`\`\``;

    // Parse CSS custom properties from the token file
    const varPattern = /--([\w-]+):\s*(#[0-9a-fA-F]{3,8})/g;
    let match: RegExpExecArray | null;
    while ((match = varPattern.exec(tokenContent)) !== null) {
      if (match[1] && match[2]) {
        colors.push({
          variable: `--${match[1]}`,
          value: match[2],
          usage: inferColorUsage(match[1]),
        });
      }
    }
  }

  const colorTable = colors.length > 0
    ? colors.map((c) => `| \`${c.variable}\` | \`${c.value}\` | ${c.usage} |`).join(`\n`)
    : `| (extract after component library generation) | | |`;

  return `# Color Palette

> Auto-generated on ${now}
> Design: ${selectedDesign.chosen.name}

## Quick Reference

| Variable | Value | Usage |
|----------|-------|-------|
${colorTable}

## Design Tokens (SCSS)

${tokenBlock}

## Design Source

- **Stitch URL:** [${selectedDesign.chosen.previewUrl}](${selectedDesign.chosen.previewUrl})
- **Inspiration:** ${selectedDesign.inspiration.title}
`;
}

function inferColorUsage(varName: string): string {
  if (varName.includes(`primary`)) return `Primary brand color`;
  if (varName.includes(`accent`)) return `Accent / interactive highlights`;
  if (varName.includes(`background`) || varName.includes(`bg`)) return `Background surface`;
  if (varName.includes(`surface`)) return `Card / panel surface`;
  if (varName.includes(`text`)) return `Text color`;
  if (varName.includes(`border`)) return `Borders and dividers`;
  if (varName.includes(`success`)) return `Success / active status`;
  if (varName.includes(`warning`)) return `Warning status`;
  if (varName.includes(`error`) || varName.includes(`danger`)) return `Error / danger status`;
  if (varName.includes(`info`)) return `Info / neutral status`;
  if (varName.includes(`muted`)) return `Muted / secondary text`;
  if (varName.includes(`shadow`)) return `Shadow definitions`;
  if (varName.includes(`nav`) || varName.includes(`sidebar`)) return `Navigation surface`;
  return `UI element`;
}
