/**
 * A design scraped from Dribbble search results.
 */
export interface DribbbleDesign {
  readonly title: string;
  readonly url: string;
  readonly imageUrl: string;
  readonly author: string;
  readonly description: string;
  readonly tags: readonly string[];
}

/**
 * A design generated by Google Stitch.
 */
export interface StitchDesign {
  readonly id: string;
  readonly name: string;
  readonly previewUrl: string;
  readonly editUrl: string;
  readonly thumbnailDataUri: string;
  readonly description: string;
}

/**
 * The design the user selected from the Stitch candidates.
 */
export interface SelectedDesign {
  readonly source: `dribbble` | `stitch`;
  readonly inspiration: DribbbleDesign;
  readonly chosen: StitchDesign;
}

/**
 * A single entry in the generated component library.
 */
export interface ComponentLibraryEntry {
  readonly name: string;
  readonly selector: string;
  readonly category: ComponentCategory;
  readonly files: readonly ComponentLibraryFile[];
}

export type ComponentCategory =
  | `token`
  | `layout`
  | `navigation`
  | `form`
  | `data-display`
  | `feedback`
  | `overlay`
  | `utility`;

export interface ComponentLibraryFile {
  readonly path: string;
  readonly content: string;
}

/**
 * The full component library extracted from the selected design.
 */
export interface ComponentLibrary {
  readonly designTokens: ComponentLibraryFile;
  readonly components: readonly ComponentLibraryEntry[];
}
