/**
 * A design scraped from Dribbble search results.
 */
export interface DribbbleDesign {
  readonly title: string;
  readonly url: string;
  readonly imageUrl: string;
  readonly author: string;
  readonly description: string;
  readonly tags: readonly string[];
}

/**
 * A design generated by Google Stitch.
 */
export interface StitchDesign {
  readonly id: string;
  readonly name: string;
  readonly previewUrl: string;
  readonly editUrl: string;
  readonly thumbnailDataUri: string;
  readonly description: string;
}

/**
 * The design the user selected from the Stitch candidates.
 */
export interface SelectedDesign {
  readonly source: `dribbble` | `stitch`;
  readonly inspiration: DribbbleDesign;
  readonly chosen: StitchDesign;
}

/**
 * A single entry in the generated component library.
 */
export interface ComponentLibraryEntry {
  readonly name: string;
  readonly selector: string;
  readonly category: ComponentCategory;
  readonly files: readonly ComponentLibraryFile[];
}

export type ComponentCategory =
  | `token`
  | `layout`
  | `navigation`
  | `form`
  | `data-display`
  | `feedback`
  | `overlay`
  | `utility`;

export interface ComponentLibraryFile {
  readonly path: string;
  readonly content: string;
}

/**
 * The full component library extracted from the selected design.
 */
export interface ComponentLibrary {
  readonly designTokens: ComponentLibraryFile;
  readonly components: readonly ComponentLibraryEntry[];
}

// ── Style Guide (Box Model Decomposition) ──────────────────────────

/**
 * A single color extracted from the design with usage context.
 */
export interface StyleGuideColor {
  readonly hex: string;
  readonly usage: string;
}

/**
 * Typography spec for a single heading/body level.
 */
export interface TypographySpec {
  readonly level: string;
  readonly fontFamily: string;
  readonly fontSize: string;
  readonly fontWeight: string;
  readonly color: string;
  readonly lineHeight: string;
}

/**
 * Spacing tokens extracted from the design.
 */
export interface SpacingSpec {
  readonly gridGap: string;
  readonly sectionPadding: string;
  readonly cardMargin: string;
}

/**
 * A single UI element decomposed from the Stitch design.
 */
export interface StyleGuideElement {
  readonly element: string;
  readonly properties: Record<string, string>;
}

/**
 * The full style guide extracted via box model decomposition of
 * the chosen Stitch design. This is the single source of truth
 * that every generated component references.
 */
export interface StyleGuide {
  readonly elements: readonly StyleGuideElement[];
  readonly typography: readonly TypographySpec[];
  readonly spacing: SpacingSpec;
  readonly colorPalette: readonly StyleGuideColor[];
  readonly rawMarkdown: string;
}
